### ISSUE TITLE
Portfolio GIF's

### ISSUE THREAD

**Issue by b3u** [umihico/thumbnailed-portfolio-websites#25]
I am honored that you stared my portfolio for your GIF Project. However, I would prefer that you ask me before reusing it. Opening an issue, for example. Please don't take this the wrong way. Thanks.
P.S. How do you make the GIF's? I want to put my site on dribbble.

**Comment by umihico** [comment]
Thank you for issuing.  Your point make sense. I definitely should be respectful to all creators.
Do you have suggestion? I don't think issuing everybody is not possible due to amount and time.

My goal is win-win relationship like what Google does. News companies want Google to copy their articles to get more visitors. I think limiting content on my page makes visitor go to creator's pages, such as only low quality GIF and links.

the answer of your P.S:
this time I use scraping which is selenium+chrome(taking screenshots)+PIL
It's all in url_to_gif function in scraping.py
If you wanna do only once easily, [LICEcap](https://www.cockos.com/licecap/) and [ezgifcom](https://ezgif.com/resize) is my recommandation
Please feel free to ask again anything if you have any questions

**Comment by lalaithan** [comment]
> 
> 
> Thank you for issuing. Your point make sense. I definitely should be respectful to all creators.
> Do you have suggestion? I don't think issuing everybody is not possible due to amount and time.

Perhaps a tag and a yes/no response to those you have scraped in your GitHub repo?

**Comment by lalaithan** [comment]
Yeah, that's the idea. I've gotten notifications from issues before. I can't click the checkbox so I'm not sure how to do that part efficiently.

**Comment by umihico** [comment]
@lalaithan 
Just let me tell you I caused lot of problem here.
https://github.com/umihico/thumbnailed-portfolio-websites/issues/26

**Comment by juanjoserendon13** [comment]
Do you have in mind to give style to the project?, is interesting see the portfolios of so many people, but also I agree with the fact that you should have asked first before use the projects.

**Comment by lalaithan** [comment]
> 
> 
> @lalaithan
> Just let me tell you I caused lot of problem here.
> #26

Yes, I received all of the emails too. I suggest exploring GitHub's knowledge base before trying out  options to see how they will work. Don't let it get to you though, we all make mistakes.

**Comment by umihico** [comment]
@juanjoserendon13 
No specific plans yet. I'd like to know people's options.
I don't think it's big problem for creators while visitors have to visit their pages eventually to get detail. I also think getting permission one by one is not practical.

**Comment by umihico** [comment]
I'm back! I had to delete two issues to unflag my account thru github. Let me apologize again about being annoying by notifications and disappeared for a days. Thank you!

**Comment by jeroentvb** [comment]
> No specific plans yet. I'd like to know people's options.
> I don't think it's big problem for creators while visitors have to visit their pages eventually to get detail. I also think getting permission one by one is not practical.

I think you should at least look into notifying people that their portfolio website is being featured on your website. 
Can't you create and issue on the owners repo if the scrape was succesful?
I only found out because you starred my repo and I'm still debating whether I like my portfiolo website being on there..

**Comment by umihico** [comment]
I apologize if you feel bad. At first, Let me tell you I'm coding right now to delete yours and implementing deletion function. Your guess are right that editing db.json make sense but we need to exclude the names next time by specifying somewhere, but their privacy matter. I'm thinking hashed usernames can be okay to write.

I need to think and wait other opinions more. I created more official-ish title issues [here](https://github.com/umihico/thumbnailed-portfolio-websites/issues/31) and will close this issue soon.
Thank you for your opinion.
